### ISSUE TITLE
How to hide information

### ISSUE THREAD

**Issue by xDanilor** [NOTIF-API/scp-600v#3]
How do i hide that SCP600 is SCP600? Because just by looking at the player impersonating SCP600 it says "SCP600", so class d immetiately detect and kill him.

**Comment by NOTIF-API** [comment]
sorry, I forgot about this possibility so that you can hide the scp-600 role, I will release a fix, thanks for reminding me about such an important flaw

**Comment by xDanilor** [comment]
> sorry, I forgot about this possibility so that you can hide the scp-600 role, I will release a fix, thanks for reminding me about such an important flaw

no problem, my pleasure

**Comment by NOTIF-API** [comment]
@xDanilor 
```yaml
visible_scp_name: false
```
by setting this parameter to false you can remove the visibility that the scp-600 player is hovered over
